apiVersion: v1
kind: Secret
metadata:
  name: beeper-frontend-secrets
type: Opaque
data:
  NEXT_PUBLIC_IS_MAINT_MODE: ZmFsc2U=
  NEXT_PUBLIC_DYNAMIC_HOMEPAGE: dHJ1ZQ==
  MAILCHIMP_API_KEY: MWRhNmM3YTY4MTJlZmJmOTUyOTM4NTdlZWIyNzM0MTgtdXM2
  MAILCHIMP_AUDIENCE_ID: ZjkzZWU3ZWZhOA==
  MAILCHIMP_CLIENT_KEY: MWRhNmM3YTY4MTJlZmJmOTUyOTM4NTdlZWIyNzM0MTgtdXM2
  MAILCHIMP_ID: ZjkzZWU3ZWZhOA==
  MAILCHIMP_U: YTAyMTcxN2U0YmJjZmQwNDliYTEwMWQyOA==
  MAILCHIMP_URL: aHR0cHM6Ly9idXp6LnVzNi5saXN0LW1hbmFnZS5jb20vc3Vic2NyaWJlL3Bvc3Q=
  MAILCHIMP_USERNAME: dXM2
  NEXT_PUBLIC_APP_URL: aHR0cHM6Ly9iZWVwZXIuYnV6eg==
  NEXT_PUBLIC_COMING_SOON_COPY: UGxheSBXaXRoIE11c2lj
  NEXT_PUBLIC_COMPANY_LEGAL_URL: aHR0cHM6Ly9iZWVwZXIuYnV6ei9sZWdhbA==
  NEXT_PUBLIC_COMPANY_PHONE: KzEgKDkxNykgMzAwLTgxMDM=
  NEXT_PUBLIC_COMPANY_EMAIL: aGV5QGJlZXBlci5idXp6
  NEXT_PUBLIC_DARK_MODE: dHJ1ZQ==
  NEXT_PUBLIC_FACEBOOK_SLUG: YmVlcGVyLmJ1eno=
  NEXT_PUBLIC_FB_PIXEL_ID: OTY1OTM0OTg0NjY4NjMz
  NEXT_PUBLIC_GA_DEBUG_MODE: ZmFsc2U=
  NEXT_PUBLIC_GA_TRACKING_CODE: Ry02SFkzVEI3M1Az
  NEXT_PUBLIC_GOHIGHLEVEL_API_URL: aHR0cHM6Ly9yZXN0LmdvaGlnaGxldmVsLmNvbS92MQ==
  NEXT_PUBLIC_GOHIGHLEVEL_API_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnNiMk5oZEdsdmJsOXBaQ0k2SWsxNFFqaFlVbHB6VjBkS1EzRk1kM2d4V0ZKU0lpd2lZMjl0Y0dGdWVWOXBaQ0k2SW1NM01uZ3hOR2hwWlVwaWNYbzFNVmxCWXpVM0lpd2lkbVZ5YzJsdmJpSTZNU3dpYVdGMElqb3hOamcxTmpZeU5qRXhNelE0TENKemRXSWlPaUoxYzJWeVgybGtJbjAuQzZaeWl3bHBqYTN5M2liZnhGSlBPeGRLTzNiVkZvT2lrNGIwR0ZMbFJxUQ==
  NEXT_PUBLIC_GOHIGHLEVEL_FORM_ID: RTljdk92QlI0bHpoOThiNVhRTk4=
  NEXT_PUBLIC_GOHIGHLEVEL_LOCATION_ID: TXhCOFhSWnNXR0pDcUx3eDFYUlI=
  NEXT_PUBLIC_INSTAGRAM_SLUG: YmVlcGVyLmJ1eno=
  NEXT_PUBLIC_LOGO_PATH: L2ltYWdlcy9iZWVwZXItbG9nby12Mi5wbmc=
  NEXT_PUBLIC_MAILCHIMP_API_KEY: MWRhNmM3YTY4MTJlZmJmOTUyOTM4NTdlZWIyNzM0MTgtdXM2
  NEXT_PUBLIC_MAILCHIMP_AUDIENCE_ID: ZjkzZWU3ZWZhOA==
  NEXT_PUBLIC_MAILCHIMP_CLIENT_KEY: MWRhNmM3YTY4MTJlZmJmOTUyOTM4NTdlZWIyNzM0MTgtdXM2
  NEXT_PUBLIC_MAILCHIMP_ID: ZjkzZWU3ZWZhOA==
  NEXT_PUBLIC_MAILCHIMP_U: YTAyMTcxN2U0YmJjZmQwNDliYTEwMWQyOA==
  NEXT_PUBLIC_MAILCHIMP_URL: aHR0cHM6Ly9idXp6LnVzNi5saXN0LW1hbmFnZS5jb20vc3Vic2NyaWJlL3Bvc3Q=
  NEXT_PUBLIC_MAILCHIMP_USER: dXM2
  NEXT_PUBLIC_MAILER: Z29oaWdobGV2ZWw=
  NEXT_PUBLIC_OG_IMG_HEIGHT: Mzcy
  NEXT_PUBLIC_OG_IMG_PATH: L2ltYWdlcy9iZWVwZXItb2ctaW1hZ2UucG5n
  NEXT_PUBLIC_OG_IMG_WIDTH: Mzcy
  NEXT_PUBLIC_PAGE_DESC: UGxheSBXaXRoIE11c2lj
  NEXT_PUBLIC_PAGE_TITLE: QmVlcGVy
  NEXT_PUBLIC_SITE_SUBTITLE: UGxheSBXaXRoIE11c2lj
  NEXT_PUBLIC_SITE_TITLE: QmVlcGVy
  NEXT_PUBLIC_SITE_URL: aHR0cHM6Ly9iZWVwZXIuYnV6eg==
  NEXT_PUBLIC_TWITTER_SLUG: YmVlcGVyLmJ1eno=
  NEXT_PUBLIC_SPREE_API_URL: aHR0cHM6Ly9hZG1pbi5iZWVwZXIuYnV6eg==
  SPREE_API_URL: aHR0cHM6Ly9hZG1pbi5iZWVwZXIuYnV6eg==
  NEXT_PUBLIC_SPREE_API_URL: aHR0cHM6Ly9hZG1pbi5iZWVwZXIuYnV6eg==
  SPREE_API_URL: aHR0cHM6Ly9hZG1pbi5iZWVwZXIuYnV6eg==
  NEXT_PUBLIC_SPREE_ACCESS_TOKEN: MGMzYjE5NWI1ODE4NTg2OGU3YjM0NTU4NWU5ZDg2ODUzM2M4Y2JkNDY1YjE1ZmMw
  NEXT_PUBLIC_IS_MAINT_MODE: ZmFsc2U=
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: cGtfdGVzdF9IZ3VFM0JYc0JWUWVldld2cEx6N20zZWE=
